### ISSUE TITLE
Minor errors 

### ISSUE THREAD

**Issue by lliknart** [Neo23x0/auditd#1]
Hi,

First of all, thank you for this auditd configuration file.
I use auditbeat running on Ubuntu 16.04 and get some errors when I load this configuration file.

**Errors:**
- Duplicate rules :  this rule is present twice: 
`-w /etc/sysconfig/network -p wa -k network_modifications
`

- Unknown user chrony : the user is _chrony on Ubuntu 16.04

**Correction:** 
- Delete the duplicate rule
- Change _chrony_ by __chrony_

**Comment by Neo23x0** [comment]
https://github.com/Neo23x0/auditd/commit/c1b6620b48d46756d51cd3fb4d754e0fb8f10f88

**Comment by alexjfisher** [comment]
On RHEL/CentOS, the user *is* `chrony` though.
