### ISSUE TITLE
augenrules - Filtering

### ISSUE THREAD

**Issue by sargenthp** [Neo23x0/auditd#17]
Hello,

I was wondering if we could get augenrules to be a little smarter with filtering rules coming in.  I found that a blank line with a simple tab or 2 will cause the process to fail.  Also a duplicate rule in 2 different rule files will cause it to fail as well.  I would like to see these filtered out.

Thanks!

**Comment by Neo23x0** [comment]
Isn't this an issue for the augenrules developers?

**Comment by sargenthp** [comment]
Wrong location.  Sorry.
