### ISSUE TITLE
linux kernel oops

### ISSUE THREAD

**Issue by turbo-cafe** [Neo23x0/auditd#27]
starting with v5.11.7 kernel goes into oops mode starting auditd service. Sorry I don't have more specific information since I don't know how to debug auditd rules.

**Comment by fintzd** [comment]
Can you post up a bit more details about what you mean by that (sorry, maybe it's only me but I'm not sure I understand this correctly). Thank you!

**Comment by turbo-cafe** [comment]
When using audit.rules from the repo I wasnt able to boot PC, like I used to, with newer kernels (started with 5.11.7). With rules imported and auditd service active kernel would panic (specifically it goes into oops mode) and fail to boot into desktop. Because of that I stopped using audit.rules with kernels > 5.11.7, I'm sorry I lack skill to provide debug information.

**Comment by kovacs-andras** [comment]
@turbo-cafe  which distro are you using right now?
I have a Fedora33 installed (5.14.9-100.fc33.x86_64) and the ruleset haven't break anything and works so far.
(Ofc it throws a few error on some missing files but that is painless.)

Try to load the ruleset manually from anywhere like:
```
auditctl -R audit.rules
```
And please, share the error what got.
Thanks!

**Comment by turbo-cafe** [comment]
@kovacs-andras I use https://getsol.us 
if I load ruleset with command above my thinkpad hangs, so no debug info

**Comment by lpirl** [comment]
Using these rules on Debian with 5.10.0-16-amd64 and 5.18.0-2-amd64 without seeing this issue.

**Comment by turbo-cafe** [comment]
Not reproducible anymore. Closing.

**Comment by turbo-cafe** [comment]
k
