### ISSUE TITLE
Auditd Service

### ISSUE THREAD

**Issue by agentsofshield** [Neo23x0/auditd#5]
Hi,
I'm trying to run the auditd service with rules based on this Best Practice on Ubuntu 16.04 and i'm having some troubles-
I started with installing the auditd package with the command: "apt-get install auditd audispd-plugins".
Next, I switched the /etc/audit/audit.rules with my audit.rules file
And finally, I restarted the auditd service: "services auditd restart"

The problem:
When I'm running the "service auditd status" command I have this message-
Active: active (running) since ......
Process: 3728 ExecStartPost=/sbin/auditctl -R /etc/audit/audit.rules **(code=exited, status=1/FALIURE)**

Please help me find the right solution.
Thank you,
AgentsOfShield

**Comment by lukefor** [comment]
On Debian derivatives you're meant to put it in a file in /etc/audit/rules.d not replace /etc/audit/audit.rules

**Comment by agentsofshield** [comment]
But unlike in RedHat the file in /etc/audit/audit.rules stays empty. It does not automatically generated from /etc/audit/rules.d/audit.rules

**Comment by agentsofshield** [comment]
I did the same in a different Ubuntu server and it worked (replaced the /etc/auditd/audit.rules)
