### ISSUE TITLE
Red Hat 8.6 errors

### ISSUE THREAD

**Issue by helpcomputer19** [Neo23x0/auditd#79]
Received the following errors on Red Hat 8.6 after reloading the rule file

`auditctl -R /etc/audit/rules.d/audit.rules`

> No rules
enabled 1
failure 1
pid 910
rate_limit 0
backlog_limit 8192
lost 0
backlog 1350
backlog_wait_time 60000
backlog_wait_time_actual 17852
enabled 1
failure 1
pid 910
rate_limit 0
backlog_limit 8192
lost 0
backlog 941
backlog_wait_time 60000
backlog_wait_time_actual 17852
-F missing operation for -k
There was an error in line 66 of /etc/audit/rules.d/audit.rules
-F missing operation for -k
There was an error in line 67 of /etc/audit/rules.d/audit.rules
-F missing operation for -k
There was an error in line 68 of /etc/audit/rules.d/audit.rules
-F missing operation for -k
There was an error in line 69 of /etc/audit/rules.d/audit.rules
-F missing operation for -k
There was an error in line 70 of /etc/audit/rules.d/audit.rules
Unknown user: ntp
There was an error in line 147 of /etc/audit/rules.d/audit.rules
Unknown user: ntp
There was an error in line 148 of /etc/audit/rules.d/audit.rules
Error sending add rule data request (No such file or directory)
There was an error in line 554 of /etc/audit/rules.d/audit.rules
Error sending add rule data request (No such file or directory)
There was an error in line 559 of /etc/audit/rules.d/audit.rules
Error sending add rule data request (No such file or directory)
There was an error in line 562 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 641 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 642 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 653 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 654 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 655 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 656 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 663 of /etc/audit/rules.d/audit.rules
Append rule - bad keyword entry,always
There was an error in line 664 of /etc/audit/rules.d/audit.rules

**Comment by kovacs-andras** [comment]
Some of these errors have been fixed. Please, check the latest commit in the master!

This amount of error is normal if you just apply the ruleset 1:1 on your server which I really don't recommend for multiple reasons.
- many of these rules makes 0 sense on RHEL so you won't get more info about your system
- but more rules means bigger impact on your server's performance

Apart from the errors, you can check which rules are in use and could be applied like: 
`auditct -l
`
We can go trough on all the errors if you want, but first fetch the latest ruleset!
Some of these are pretty obvious anyways:
 "_Unknown user: ntp_" of course it's unkown, you have the _chrony_ user for the same reason.

**Comment by helpcomputer19** [comment]
Thanks @kovacs-andras! The latest commit and removing unneeded rules helped.
