### ISSUE TITLE
Auditd doesn't save new rules.

### ISSUE THREAD

**Issue by thecowmilk** [Neo23x0/auditd#81]
I have an Ubuntu 20.04 and installed `auditd` on it and I wanna set some rules on `audit.rules` file but eveyrtime I restart the service the file will rewritten to the default one. How can I keep my modified `audit.rules` file?

**Comment by meiswjn** [comment]
I think you need to put it in the folder /etc/audit/rules.d/

**Comment by kovacs-andras** [comment]
This is not a valid issue an even if it would be should go here: https://github.com/linux-audit/audit-userspace/issues
But it has nothing to do with that project either. Check the Ubuntu 20.04 specific service unit:
```
# systemctl cat auditd.service | grep ^ExecStartPost
ExecStartPost=-/sbin/augenrules --load
```
then `man augenrules`
_augenrules  is  a  script  that merges all component audit rules files, found in the audit rules directory, /etc/audit/rules.d, placing the merged file in /etc/audit/audit.rules.
. . . 
**The generated file is only copied to /etc/audit/audit.rules, if it differs.**_

In your case, it did. This ExecStartPost step can be changeable on different Linux distros. Canonical probably set this with good intention to save you an extra step -> loading the new rules.

**Comment by thecowmilk** [comment]
> This is not a valid issue an even if it would be should go here: https://github.com/linux-audit/audit-userspace/issues But it has nothing to do with that project either. Check the Ubuntu 20.04 specific service unit:
> 
> ```
> # systemctl cat auditd.service | grep ^ExecStartPost
> ExecStartPost=-/sbin/augenrules --load
> ```
> 
> then `man augenrules` _augenrules is a script that merges all component audit rules files, found in the audit rules directory, /etc/audit/rules.d, placing the merged file in /etc/audit/audit.rules. . . . **The generated file is only copied to /etc/audit/audit.rules, if it differs.**_
> 
> In your case, it did. This ExecStartPost step can be changeable on different Linux distros. Canonical probably set this with good intention to save you an extra step -> loading the new rules.

Yes absolutely you are correct! Thank you for your time and perfect explanation. I fixed this a long time ago tbh by putting the rules in the rules.d directory.

At that time I was still a beginner using audit and I apologise for the beginner question. Everyday I learn something new and improve and I’m here for it!
